### ISSUE TITLE
getTranslation to return string Type

### ISSUE THREAD

**Issue by ieow** [ryandrewjohnson/react-localize-redux#11]
Hi, 
getTranslation is define to return LocalizedElement type
returns (key | key[], data) => LocalizedElement | { [key: string]: LocalizedElement }

Is there a way to return string type only?
Thanks

**Comment by ryandrewjohnson** [comment]
In order to allow for the rendering of HTML inside translation strings it needs to be returned as an element. I will look into maybe only returning an element when HTML is detected in the translation, and for other scenarios it would just return a string.

Would that satisfy your ask?

**Comment by ieow** [comment]
Actually, if there is an option for me to choose String type would be good enough.
I am now using `LocalizedElement.props.children` which is not a good solution.

**Comment by ryandrewjohnson** [comment]
I have updated the translate function to return a string when a translation does not include HTML. In the case where a translation contains HTML it will still return the translation wrapped in a `<span>` tag like it did previously.

I have also updated the README for [getTranslate](https://github.com/ryandrewjohnson/react-localize-redux#gettranslatestate) to explain this.

I chose this route instead of adding an option because:
1. Keeps the API the same - no changes needed
2. In order to render HTML contained in translations it has to be wrapped in a React element anyway.

You can find the changes in v2.3.0.

**Comment by ieow** [comment]
Cool. Thanks. Tested. :)
