### ISSUE TITLE
Combined use of SSR and redux

### ISSUE THREAD

**Issue by qeterlee** [ryandrewjohnson/react-localize-redux#143]
**Do you want to request a _feature_ or report a _bug_?**
Not sure if it is a bug.

**What is the current behavior?**
When configuring react-localize-redux to work with SSR **and** redux the initial state in the initialize attribute of LocalizeProvider is not stored in redux. Thus the first server side rendered content is missing the initialization.

**Where does the problem occur?**
We are using the following SSR boiler plate: [https://github.com/bertho-zero/react-redux-universal-hot-example](https://github.com/bertho-zero/react-redux-universal-hot-example)
In src/server.js we added LocalizeProvider:
```
      <Loadable.Capture report={moduleName => modules.push(moduleName)}>
        <Provider store={store} {...providers}>
          <LocalizeProvider store={store}  initialize={{
              languages,
              options: {
                defaultLanguage: "EN",
                renderToStaticMarkup: renderToStaticMarkup
              }
            }}>
            <ConnectedRouter history={history}>
              <ReduxAsyncConnect routes={routes} store={store} helpers={providers}>
                {renderRoutes(routes)}
              </ReduxAsyncConnect>
            </ConnectedRouter>
          </LocalizeProvider>
        </Provider>
      </Loadable.Capture>
```
**What is the expected behavior?**
Redux store should be initialized using the initialize attribute of the LocalizeProvider. Since in the boiler plate store.getState is used to inject the initial state for the first SSR content.

Does react-localize-redux support SSR **and** redux simultaneously?

**Which versions of `react` and `react-localize-redux` are you using?**
react: 16.0.0
react-localize-redux: 3.5.1

**Comment by thchia** [comment]
@qeterlee is it possible to provide a reproduction for this issue? It sounds like something that should have been fixed in #136 but if you are having issues then let's investigate.

**Comment by qeterlee** [comment]
Hi @thchia thank you for your fast response!

I missed #136, maybe I have a configuration issue. However I still created a running example using that boilerplate: https://github.com/qeterlee/localize.git

And this should start the example:
```
yarn
yarn dev
```

When javascript is deactivated in the browser, I see in the first page load that in the window.__data variable the initialisation of localize is missing. Have I missed something? Thank you for your help!

**Comment by thchia** [comment]
@qeterlee Ok, the short answer is that this behaviour is expected.

When you server-render your application, it will generate static HTML that is sent back down to the browser. Setting up the redux store is a separate concern that you must handle if you want it to contain certain data upon hydration (like the localization data in this case).

After digging through the boilerplate you are using, I've discovered the use of the [redial](https://www.npmjs.com/package/redial) library, which exposes an API that lets you dispatch actions during the server rendering process. You can look for the `@provideHooks` decorators to see what I mean.

As you can see, the boilerplate author is using this to dispatch actions related to `auth` and a contrived `loadInfo` module. This is why `window.__data` contains the message `This message comes from the api server`, as well as a bunch of auth errors.

In order for you to achieve this for your own functionality, you will need to dispatch the `initialize` action from one of these `@provideHooks` decorators. For example in `containers/App/App.js`:

```jsx
import { initialize } from 'react-localize-redux'

@provideHooks({
  fetch: async ({ store: { dispatch, getState } }) => {
    await dispatch(initialize({
      // languages, options, etc.
    }))
    // ...
  }
})
```
The considerations for this approach are
1. `initialize` export is not documented, not sure if it is going to be removed, but it is required for this (cc @ryandrewjohnson is it safe to dispatch the `initialize` action directly?)
2. This library initializes the store in `componentDidMount`, hence why it does not initialize on the server. Moving this to the constructor would solve this problem (and mean you don't have to make any code changes I think...), but I'm not sure if dispatching actions in the constructor is an antipattern. I don't have much experience with SSR and thus don't know what the canonical way to address this is.
I suspect it is NOT for us to move the initialization into the constructor, but for you to do something like the snippet I posted (in fact it seems like this is why the redial library exists!).

Hope that clears things up, did my best to explain what I think the issue is 🙂

**Comment by qeterlee** [comment]
@thchia thank you for the nice explanation. I understand it now and I will try to implement a solution according to your given code snippet. I also will close this issue now. Keep up the great work!
