### ISSUE TITLE
Translate property of jsx element

### ISSUE THREAD

**Issue by boetn** [ryandrewjohnson/react-localize-redux#145]
Hi, I just started using your library and it has been great so far. I do have a feature request / "can I do this question".

I was trying to assign a translated text to the placeholder property of an input element. however I can't seem to get it working.

```javascript
const placeholder = <Translate id={'search'} />;

return (
     <input type="text" className="form-control" placeholder={placeholder} />
);
```

This however shows a `[object] [Object]` placeholder since an object is returned. Is there any way I can accomplish this without moving my complete input element to my translation file?

**Comment by ryandrewjohnson** [comment]
You need to use the [translate](https://ryandrewjohnson.github.io/react-localize-redux-docs/#translate) function, which can be accessed by either using the [Render Props](https://ryandrewjohnson.github.io/react-localize-redux-docs/#render-props-api) version of `<Translate />` or the [withLocalize](https://ryandrewjohnson.github.io/react-localize-redux-docs/#withlocalize) HOC.

With render props:

```javascript
return (
  <Translate>
   {({ translate }) => <input type="text" className="form-control" placeholder={translate('search')} />}
 </Translate>
);
```

**Comment by Cookst3r** [comment]
@ryandrewjohnson, Following my previous issue ( https://github.com/ryandrewjohnson/react-localize-redux/issues/146#issuecomment-462599763, marked as duplicate to this one) I am still unable to return a plain string.

![image](https://user-images.githubusercontent.com/33281770/52643674-680b6600-2ed5-11e9-95a4-3c3b02055e3b.png)


```ts
return (
      <Translate>
        {({ translate }) => (
            <option value={translate('salutations.default')}>
              {translate('salutations.default')}
            </option>
        )}
      </Translate>
    );
```
The issue is passing the translation to the value attribute of the option

dictionary file for the saluations
![image](https://user-images.githubusercontent.com/33281770/52643607-4ca05b00-2ed5-11e9-8aab-03f73c6d73e5.png)

is giving me error

![image](https://user-images.githubusercontent.com/33281770/52643462-fa5f3a00-2ed4-11e9-948d-58da0f125785.png)

could you advise if I am doing something wrong please as this seems to be as described in the docs.

Thank you for any help you can provide and apologise if I am missing something simple
