### ISSUE TITLE
Pros/Cons with react-intl and react-intl-redux

### ISSUE THREAD

**Issue by mjsisley** [ryandrewjohnson/react-localize-redux#21]
Thanks for doing OSS!

I'm curious what are the pros/cons of this library compared to https://github.com/yahoo/react-intl and https://github.com/ratson/react-intl-redux? Maybe adding something to the README would be helpful.

**Comment by ryandrewjohnson** [comment]
To be honest I wouldn't be 100% comfortable writing any sort of formal comparison, as I have no experience with either of these other libraries. If you have a lot of experience with either feel free to contribute your thoughts, and I could look at updating the README. In the meantime here are some general differences based on just having a quick look at the docs for these two...

**react-intl**
* This library is much larger, and for good reason as it handles many things related to localization. e.g. Pluralization, currency. Where as with react-localize-redux you could still do pluralization, and currency, but you'd be writing the formatting functionality yourself. For rough comparison `react-intl.min.js` is `41kb`, while `react-localize-redux` is `11kb`. 
* It does not meant to work with Redux out of the box, but does have an additional library that will integrate it with Redux.

**react-intl-redux**
* This is just the aforementioned library that allows you to integrate `react-intl` with Redux. So you would need to install this library as well as `react-intl` adding even more weight.

Hope that helps a bit.

**Comment by mjsisley** [comment]
Thanks!

Honestly, that brief description is pretty helpful. I think adding something like this to the README would be helpful for those quickly browsing. I think it is helpful to reduce the time for the user to identify that this is a lighter weight alternative for a react redux internationalization library than react-intl (from yahoo) and react-intl-redux.

**Comment by ryandrewjohnson** [comment]
Yea I like the idea. When I get some time I'll look in more detail at those other libraries, and then I'll feel more comfortable putting something official in the docs. For now I'll keep this open to track that.

**Comment by pke** [comment]
Thanks for this library too! I had a look at react-intl a while ago but never got around implementing i18n in my apps. Now I wonder why I would have to have translations in the redux store? The only benefit I see is the instant re-translate function it brings with it when one changes the language on the fly.

If the language is determined by the browsers language setting only once, when the page is loaded then one could just load the translations files and have them accessible all the time inside a module.

````
/// i18n.js

const translations = {}

export const add  = file => {
  return new Promise(c, {
     require.ensure(...load file)
  })
}

export default (key, vars) => (
  findInTranslations(translations, key, vars)
)



// In index.js
import { add } from "i18n"

// Load file based on navigator language setting
add(navigator.language)

// In any component
import _ from "i18n"
const Article = () => (
  <article><h1>{_("article.title")}</h1></article>
)
```` 

This would not support on-the-fly i18n but do the job otherwise?

**Comment by ryandrewjohnson** [comment]
Will try my best to answer some of your questions, but first like implementing any feature there’s usually many ways to do it. By know means is react-localize-redux the only way - go with whatever works for you.

Why would I have my translations in redux store?
For me if I’m already using Redux it makes sense to store this data in Redux. It gives my entire app access to all the data without having to pass it down, and I don’t have to use context. If you’re not using Redux anywhere else in your app then obviously I would not recommend using this library. 

In terms of example you provided, if that works for you then by all means roll with it again what’s important is it works for you. But here are a few things that react-localize-redux (RLR) might provide that this might not cover:

1. RLR allows for splitting translation data into multiple files, and then lazy loading when needed. But all translations are added to the store, so all components have access to them once loaded.

2. Ability to do variable replacement in translation data, as well as automatic HTML detection for rendering HTML string data.

3. Configure callback for missing translations.

4. Because it’s using Redux all connected components will have access to all translation data. 

5. Supports nested data format.

6. Supports translation data transforms to support third-party data types.

If you’re not leveraging any of the above, and you’re app isn’t using Redux already then it might not be a good fit.

**Comment by Landish** [comment]
@mjsisley 

I just implemented `react-localize-redux` package in my own project. The main reason why I decided, to use this package instead of `react-intl`, was that *I was already using redux* and thought that storing languages in it would be a great idea (because UI needs to be updated, when locale changes and etc.).

Another reason why I sticked to this and not `react-intl`, was the bundle size. 

IMHO `react-localize-redux` is much more simple, flexible and small library, than `react-intl` + `react-intl-redux`. So I would definitely recommend this package, if you're using redux.

@ryandrewjohnson 

First of all, thanks for having such a great library, it saved me a lot of time last night 😅

Also, during the research, I came across this library: https://github.com/lingui/js-lingui, which has it's own CLI - [lingui-cli](https://github.com/lingui/js-lingui/tree/master/packages/lingui-cli). 

With that CLI you create locale files, and *extract* translatable strings from components into localization files. Which I think is super useful. 

Another thing that I thought your package was missing, was ability to store/retrieve `currentLanguageName` and `currentLanguageNativeName` props. 

For example, for German language, `currentLanguageName` => `German` and  `currentLanguageNativeName` => `Deutsche`.

This is pretty useful, when you have some sort of language switcher component and want to display the current language name in native or in other language. 

And with the current implementation it's a bit of a pain in a butt. You have to stored in local state or create these action/reducers manually and use them.

**Comment by ryandrewjohnson** [comment]
@pke I will try my best to answer some of your questions, but first like implementing any feature there’s usually many ways to do it. By no means is `react-localize-redux` the only way to go - use whatever works for you.

>I'm going to assume that your project is already using redux. It would be overkill to bring in `redux` and `react-redux` just to accommodate this library.

**Why would I have my translations in redux store?**

More than likely many, if not all, of your app's components will need access to translation data. In order for this to work in react you have 3 options in my opinion...

1. Manually pass the data down to child components using props. 
2. Use React's [context](https://reactjs.org/docs/context.html) 
3. Use a state management library like [redux](https://github.com/reactjs/redux) or [mobx](https://github.com/mobxjs/mobx)

If you're already using `redux`, then having your translation data in the redux store makes sense to me. This allows the data to be easily shared by all the components in your app, and `react-localize-redux` is simply a library that makes this even easier to manage.

**What else does react-localize-redux(RLR) provide?**

A full [feature list](https://ryandrewjohnson.github.io/react-localize-redux/features/) can be found in the [official docs](https://ryandrewjohnson.github.io/react-localize-redux/), but here is a quick summary...

1. RLR allows for splitting translation data into multiple files, and then lazy loading when needed. 

2. All translations are in your redux store, so all components have access to them once loaded.

3. Ability to do variable replacement in translation data, as well as automatic HTML detection for rendering HTML string data.

4. Configure callback for missing translations.

5. Supports nested data format.

7. Supports translation data transforms to support third-party data types.



If you’re not leveraging any of the features above, and your app isn't already using redux then RLR may not be the right choice for you.

Hope this helps.

**Comment by ryandrewjohnson** [comment]
@Landish thanks for the great feedback. This will be really useful when I finally get around to writing up something on `react-intl`.

In terms of `currentLanguage` issue ... do you mind opening an official feature request in issues, and providing some more detail on the functionality you're looking for?

**Comment by rockia** [comment]
Like the @ryandrewjohnson describes `react-localize-redux`, it's "Dead simple". I only spent 30 min or less to get our company website started on the i18n track. 

One thing I am worrying right now is that, I have to `connect` every component to the `translate` state as props. We just have way too many components that requires the translations. Oh well, that's how Redux works. 

THANKS for the great library. I hope I can contribute to this project one day as I am using it in production.

**Comment by ryandrewjohnson** [comment]
@rockia in regards to this statement...

> One thing I am worrying right now is that, I have to connect every component to the translate state as props. We just have way too many components that requires the translations. Oh well, that's how Redux works.

If you have a Component with many child components that require translations, I recommend that you add translate to the root component, and pass translations down to stateless child components as props. This would help avoid connecting many components. This is essentially the same strategy one would use with connect.

[See Pass multiple translations to child components in the docs for reference](https://ryandrewjohnson.github.io/react-localize-redux/features/#pass-multiple-translations-to-components).

_FYI: on a related note all the react-localize-redux selectors are using reselect behind the scenes to minimize any renders from unrelated prop changes as well._

**Comment by rockia** [comment]
@ryandrewjohnson A big THANK YOU. You just saved many hours of my work time in the near future.

**Comment by ryandrewjohnson** [comment]
I have added a new [FAQ page](https://ryandrewjohnson.github.io/react-localize-redux/faq/#how-does-react-localize-redux-differ-from-react-intl) to the docs that includes a question related to this topic, and have included some of the point from the discussion here. 

If you have any further insight on this topic feel free to update the docs and submit a PR.

**Comment by ryandrewjohnson** [comment]
@rockia I have also added your topic as a FAQ question as it's come up before. Let me know if you think there is anything that can be added. 

https://ryandrewjohnson.github.io/react-localize-redux/faq/#do-i-have-to-connect-every-component-that-needs-translations
