### ISSUE TITLE
Translations get cut off after 1 character.

### ISSUE THREAD

**Issue by rohan-buchner** [ryandrewjohnson/react-localize-redux#26]
Using the following I get a strange quirk...

<a href="https://ibb.co/bPLOjQ"><img src="https://thumb.ibb.co/bPLOjQ/Screen_Shot_2017_09_18_at_9_43_08_PM.png" alt="Screen_Shot_2017_09_18_at_9_43_08_PM" border="0"></a>

```
interface HomePageState {
    translate: any;
}

type HomePageProps = HomePageState

class Home extends React.Component<HomePageProps, HomePageState> {   
    /// the below will only render "I"
    public render(): any {
        return <label>{ this.props.translate("home.slogan") }</label>;
   }
}

const addTranslateToProps = state => {
    console.log('state.locale', state.locale);
    // this will log out "translations: { home.slogan: "I'm the correct translation" }
    return {
        translate: getTranslate(state.locale)
    }
};

export default connect(
    addTranslateToProps
)(Home) as typeof Home;

```

To be clear:
The translations state seems to contain the correct translation / localization, but the `translate` function exposed via props, does not work as expected.

I do believe it might be a dependent lib (reselect??) thats causing the problem, but not too sure... if anyone has encountered this before, any advice would be appreciated. I'm happy to supply any other information thats needed. 

Other info: 
Stack is on top of dotnetcore, React + Redux + SSR (with webpack for bundling front end stuff)

**Comment by ryandrewjohnson** [comment]
Would you be able to provide the following:

* what the unexpected result is you are encountering? What is being rendered for translate('home.slogan')
* a sample of your original translation data that you pass to addTranslate 
* a look at the languages array you are passing to initialize
* what version of library are you using?

Thanks

**Comment by rohan-buchner** [comment]
No problem:

This is my actual translation. (I actually scrubbed out my real translations in the previous sample, so the apostrophe shouldn't be an issue... but yolo, please see below.)

localizations.json
```
{
    "home": {
        "slogan": "Search among thousands of jobs in one place!",
        "search-label": "What are you looking for?",
        "search-button-text": "Search",
        "input-placeholder": "Search for Job Title, Location or Company"
    }
}
```

Gets loaded in my boot server like this.
```
       // get translation file
        const json = require('./localizations.json');
        store.dispatch(initialize(['localizations'], { defaultLanguage: 'localizations'}));
        store.dispatch(addTranslation(json));
```

I'm using 2.10 (as of last night, prior i was on 2.8... but same issue)

**Comment by ryandrewjohnson** [comment]
Ok this helped thanks for sending over.

The main issue appears that you are using the wrong action to add your translations. You are using "addTranslation", but you should be using "addTranslationForLanguage". This is because you're adding translations in the "single language format". If you haven't already, make sure to review the Formatting Translation Data section in the docs 
https://ryandrewjohnson.github.io/react-localize-redux/formatting-translation-data/

In addition to this there are some oddities in the way you initialized things:

1. It appears that you have only passed a single language to initialize. I'm going to assume that you'll be adding more languages later? 

2. The single language you passed is called "localizations", which will work but the intention is this should be an identifier for  the language. (E.g. en, en-US, english) etc..

3. You passed in a defaultLanguage setting to initialize, but by default the first language you pass to initialize will already be the default. The only time you need to pass defaultLanguage is if you want it to be something other than the first language in the array of languages.

Hope that helps.

**Comment by rohan-buchner** [comment]
Thank you... feel so dumb for missing that O_o

It's working. Thank you for the guidance (writing it off to 3, 12 hour days)

1. Not sure yet, It might be sufficient for me to swap out the same file as part of my build process (eg the users wont have the option to change localization (or in my case app branding))

2. See above, i'm in effect building a white label portal, and I'm using the localize/translation feature to swap out new app lables

3. My TypeScript / webpack build was b*tching about it... not sure why :/

Thanks for this awesome lib. (It actually wasn't too tough to get up an running... albeit my ~scrappy~ doc reading abilities :P

**Comment by ryandrewjohnson** [comment]
Glad it worked out. I think I'm going to try and tighten up the typings for the translation data, as that might help catch this issue for anyone using TypeScript or Flow.
