### ISSUE TITLE
Example for use with Server side rendering

### ISSUE THREAD

**Issue by lmcjt37** [ryandrewjohnson/react-localize-redux#59]
Is it possible to use this library with server side rendering out of the box?

Currently receiving errors for `TypeError: Cannot read property 'code' of undefined`

**Comment by ryandrewjohnson** [comment]
I've never tried with SSR before so I'm not sure if it would work out of the box. I've done little with SSR myself, but if you're able to share your source somehow I can have a look.

**Comment by lmcjt37** [comment]
Unfortunately, it's company code and would take too long to decouple a sample to show you. Sorry. 

I managed to get it working, but I am initialising for the server and for the client...seems a little strange, but for now it's working.

**Comment by samuelg0rd0n** [comment]
@lmcjt37 Could you elaborate a bit on how you solved this? Thank you.

**Comment by ryandrewjohnson** [comment]
@samuelg0rd0n this issue was opened previous to the latest major version of the library (3.0). If you are on the latest version have a look at this open issue #103 . This issue is related to server side rendering and I really need someone who is using server side re seeing to test for me. Have a look and let me know if you can help.
