### ISSUE TITLE
Scanning the whole react app to generate a file containing all keys found

### ISSUE THREAD

**Issue by FabulousCo** [ryandrewjohnson/react-localize-redux#60]
I would like to use this package for my project, but there is a feature missing that I'd like to have with it though.

**A way to generate a file, containing all keys to translate, by scanning the whole react project and looking wherever I use the translate function.**

To give you some context:

I’d like to be able to give a default translation, that would be in English, directly in the code, scan it, generate a file, and use this file to build my own translation portal where the translators will have the list of keys to translate **with their default value** (the English version). Save the whole into a DB and use this to generate the languages.json file that would then be used in the react app for react-localize-redux.

Does that make sense ?

**Comment by ryandrewjohnson** [comment]
I have been thinking about a way to try and allow for user's to insert the default language translations directly into components instead of having to use `translate(key)`, which can be hard to interpret when trying to search by copy in components. I have only thought about this high level, but it could look something like this:

```javascript
<translate key="greeting">hello</translate>
```
Then instead of the user having to set the default language through `json` it could be pulled directly from the components in the app. Again this is high level still and needs some more thought. Especially if this was going to be backwards compatible, as I think the user should have the choice to use existing method or this one.

Now in terms of what you're describing where something scans your files, and pulls out translation data and saves them to a file... that would be outside the scope of this library. This functionality would be more fitting as some sort of bundler plugin e.g.(webpack). I do like the idea though, and there is no reason a separate webpack plugin could not be combined with the new functionality I described above to potentially get what you're describing working.

Let me know your thoughts.

**Comment by FabulousCo** [comment]
That makes sense. I like the idea of the translate component containing the default text. You could also simply add second optional argument to the translate function if you want to keep it consistent though.

**Comment by ryandrewjohnson** [comment]
@FabulousCo I have just pushed a new version `v2.17.0` that has the new `<Translate />` component, which covers this request:

> I’d like to be able to give a default translation, that would be in English, directly in the code...

I have also updated the docs with a new [Translate](https://ryandrewjohnson.github.io/react-localize-redux/api/translate/) section. 

I'm going to close this feature request, as the other request regarding scanning, as mentioned previously, is outside the scope of this library.
