### ISSUE TITLE
Translate Utility func

### ISSUE THREAD

**Issue by meta-chris** [ryandrewjohnson/react-localize-redux#70]
Hello there,

First of all, wonderful work here. After reviewing the docs I began implementing this into a project and everything has been very smooth! The Translate component is my mvp; prevents me from having to hook up simpler components to the store.

One issue I've run into is translating attributes on components.
Let's take the placeholder attribute on the input element for example.

```
import { Translate } from 'react-localize-redux';
...
render() {
  return (
    <input htmlSize="32" label="" name="email" type="email" placeholder={<Translate id="placeholder1" options={{renderInnerHtml: false}}>Email Address</Translate>}/>
  );
}
```

translations.json
```
{
"placeholder1": [
		null,
		"Adresse e-mail",
		"Dirección de correo electrónico"
	]
}
```
This will cause the input placeholder to read out as `[object Object]`, as its not a string but an object.

Now I do understand that I can solve the issue in this particular example by wrapping the entire input markup in a Translate component and adding the markup to the translation data. But doing so can really muck up the translations, and and make performing updates quickly more time consuming than it should be. Perhaps more importantly, I think there's an opportunity here to improve support for React Components.

What I propose is exposing a utility function that will allow developers to translate a given string into the current active language. Something like this:

```
import { Translate, Translator } from 'react-localize-redux';
...
render() {
  return (
    <input htmlSize="32" label="" name="email" type="email" placeholder={Translator.translate("placeholder1", "Email Address")}/>
  );
}
```

where translate's signature could be something like:
```
translate(id, defaultValue, lang=currentActiveLang);
```

Having the ability to translate strings in this manner would allow them to be passed as props, thereby solving some of the other issues with React Component support by enabling more flexible patterns.

Thoughts? Is this even feasible?

**Comment by ryandrewjohnson** [comment]
First off thanks for the kind words. Now in regards to your issue if I'm understanding you correctly the [translate](https://ryandrewjohnson.github.io/react-localize-redux/api/selectors/#translatekey-string-string-data-options) function you describe actually already exists.

In order to get access to the translate function you have a few options:

Use Translate's render props API - see [Flavour 2](https://ryandrewjohnson.github.io/react-localize-redux/getting-started/#4-add-translations-to-components) example in getting started docs:

```javascript
<Translate>
  {translate =>  
     <input htmlSize="32" label="" name="email" type="email" placeholder={ translate("placeholder1") }/>
  }
</Translate>
```

You can also access the translate function directly in connected components. Again see the [Add translations to components](https://ryandrewjohnson.github.io/react-localize-redux/getting-started/#4-add-translations-to-components) in the getting started section of the docs. It's the last example after Translate's render props stuff.

**Comment by ryandrewjohnson** [comment]
Nice! I like this  syntax `translate("placeholder1") || "Email Address"` for keeping the default language while using translate - should probably add it to the docs.

Going to consider this issue closed.
