### ISSUE TITLE
Immutable JS broken on V3

### ISSUE THREAD

**Issue by gabroe** [ryandrewjohnson/react-localize-redux#82]
Looks like `LocalizeProvider` immutable stores are not supported,  if store is a Map then `localize` should be retrieved using `get('localize')`:

`const curLocalizeState = this.props.store.getState().localize;`

See: 

https://github.com/ryandrewjohnson/react-localize-redux/blob/master/src/LocalizeProvider.js#L73

**Comment by ryandrewjohnson** [comment]
I myself don't use ImmutableJS, so I'm not familiar with how it. I had someone who works with ImmutableJS help me with the v2 support. If you are an ImmutableJS user I'd appreciate if you're able to submit a PR with a fix since you'll be able to properly test it.

**Comment by gabroe** [comment]
Got it, I'll work on it hopefully this week!

**Comment by ryandrewjohnson** [comment]
Let me know if you have any questions along the way. And be sure to check out the [pull request template](https://github.com/ryandrewjohnson/react-localize-redux/blob/master/.github/PULL_REQUEST_TEMPLATE.md) for details on contributing. Looking forward to the PR - thanks again.

**Comment by ryandrewjohnson** [comment]
@gabroe any progress on this one?

**Comment by thchia** [comment]
@ryandrewjohnson if it's helpful I can roughly re-implement how it worked in v2.

It will expand the public-facing API though - since I think in v2 this was achieved by allowing the user to pass in a handler for selecting the `localize` state. I don't use ImmutableJS either so verifying will be harder (but not impossible...).

**Comment by ryandrewjohnson** [comment]
@thchia I think a similar approach can be taken that was used on v2, but instead of adding the `getState` function as an initialize option we can just have another optional param directly on `LocalizeProvider`. That way it doesn't muddy up the initialize options any further, especially since this use case will most likely only be used by redux users using ImmutableJS.

So I think it would be something like this:

```javascript
const getStateSlice = (state) => state.toJS()['localize'];

<LocalizeProvider store={store} getState={getStateSlice}>
</LocalizeProvider>
```
From there I think the only other update would be to line 73 of `LocalizeProvider` which looks like this:

```javascript
// update this to use the getState prop if defined
const curLocalizeState = this.props.store.getState().localize;
```
For tests you can definitely reference the v2 tests, as that's really the only ImmutableJS testing I did on my end. Although at that time I did have someone who was using the library with ImmutableJS to verify.

Feel free to pick this one up if you like, and let me know if you need any help. Also will need to update the docs again with this change as well. May want to consider adding a FAQ section as well like v2 [Can I use ImmutableJS?](https://ryandrewjohnson.github.io/react-localize-redux/faq/#can-i-use-immutablejs)

**Comment by thchia** [comment]
@ryandrewjohnson yup that was what I was thinking regarding the prop on the Provider.

I probably won't be able to do anything till the weekend so if you want to jump in before that please do 😄 .
